config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'lists#index'

  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, presence: true, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit Bookmark", class: "btn btn-primary" %>
<% end %>
<%= link_to 'Back', list_path(@list.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar  navbar-light bg-light">
      <a class="navbar-brand" href="#">
      <%= image_tag "popcorn2.png", width: '20%' %>
      </a>
      </button>
      <div class="d-flex">
          <a class="nav-link" href="/lists">My Lists<span class="sr-only">(current)</span></a>
          <a class="nav-link" href="/lists/new">New List</a>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= image_tag "theatre.jpg", alt: "Theatre", width: '100%', height: 400 %>
<div class="centered"><h2>Save any kind of movies<br>Classic</h2>
</div>


<br>
<br>


<div class="container">

  <div class="row">
    <div class="col-2"></div>

    <div class="col-8 d-flex justify-content-between">
      <h3>My Lists</h3>
      <a href="/lists/new" class= "btn btn-success">Create a movie list</a>
    </div>
    <div class="col-2"></div>
  </div>

  <div class = "row">
    <div class="col-4"></div>
    <div class="col-4 d-flex justify-content-between">

        <% @lists.each do |list| %>
          <div class="card" style="width: 18rem;">
            <%= cl_image_tag @list.photo.key, crop: :fill %>
            <div class="card-body">
              <p class="card-text">
              <%= link_to "#{list.name}", list_path(list) %>
              </p>
            </div>
          </div>
        <% end %>
    </div>
    <div class="col-4"></div>
  </div>
</div>

app/views/lists/new.html.erb
<div>
  <%= simple_form_for(@list) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit List", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/lists/show.html.erb
<h2>
<%= @list.name %>
</h2>

Photo: <br>
<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
<br>
<h3>
<% counter = 1 %>
Bookmarks:<br>
<% @list.bookmarks.each do |bookmark|%>

<%= counter %>. <%= bookmark.comment %>
<% counter = counter + 1 %>
<% end %>
</h3>

<%= link_to 'Back', lists_path %> | <%= link_to 'Add new bookmark', new_list_bookmark_path(@list.id) %>